services:
  # Сервис базы данных
  db:
    image: postgres:15
    container_name: movie_db_container
    environment:
      POSTGRES_DB: RecomendSystem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 192837
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d RecomendSystem"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Сервис кэширования Redis
  redis:
    image: redis:7-alpine
    container_name: movie_redis_container
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Твоё Spring Boot приложение
  app:
    build: .
    container_name: movie_app_container
    ports:
      - "8080:8080"
    environment:
      # Настройки БД
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/RecomendSystem
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 192837
      
      # Настройки Redis (используем имя сервиса 'redis' вместо localhost)
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      
      # Прочие настройки
      SPRING_LIQUIBASE_ENABLED: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate # Рекомендую сменить на validate для порядка
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy