spring.application.name=RecomendationSystem

spring.datasource.url=jdbc:postgresql://db:5432/RecomendSystem
spring.datasource.username=postgres
spring.datasource.password=192837
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

security.jwt.secret_key=4eeab38d706831be4b36612ead768ef8182d1dd6f0e14e5dc934652e297fb16a
security.jwt.access_token_expiration=36000000
security.jwt.refresh_token_expiration=252000000

scoring.weights.reaction.liked=0.2
scoring.weights.reaction.disliked=-0.1
scoring.weights.recency.week=0.6
scoring.weights.recency.month=0.3