spring.application.name=RecomendationSystem

spring.datasource.url=jdbc:postgresql://localhost:5433/RecomendSystem
spring.datasource.username=postgres
spring.datasource.password=192837

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=2

spring.data.redis.timeout=500ms
spring.data.redis.connect-timeout=1000ms